const inputRoomingDefaultData: any = {
  dataFotransactRoomDTO: [
    {
      id: 0,
      guestId: null,
      arrivalDate: null,
      departureDate: null,
      rate: 0,
      rateCode: null,
      roomType: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      fixedRate: true,
      comments: null,
      flightNo: null,
      printRate: true,
      status: 0,
      flagType: 0,
      cutOfDate: null,
      arrivalPickUp: true,
      departurePickUp: true,
      confirmed: true,
      resSource: null,
      resMarket: null,
      packageCodes: null,
      specialsCodes: null,
      isNet: true,
      guid: null,
      parentGuid: null,
      hotelId: 0,
      hotelGuid: null,
      isNoBkf: true,
      resChanel: null,
      carPickUp: null,
      carPickUpTime: null,
      companyAgentGuid: null,
      nights: 0,
      origin: null,
      resType: null,
      paymentMethod: null,
    },
  ],
};

export default inputRoomingDefaultData;
