import { ITracerMessage } from "common/model-rsvn";

export const NEW_TRACER_DEFAULT: ITracerMessage = {
    parent: 0,
    parentMe: 0,
    ngayThang: "",
    idfrom: 0,
    idto: 0,
    inHouse: 0,
    inHouseGuid: "",
    guest: "",
    reservation: 0,
    messageSubject: "",
    message: "",
    comment: "",
    status: 0,
    flagType: 0,
    dateFrom: "",
    dateTo: "",
    department: "",
    nguoiGui: "",
    ngayNhan: "",
    nguoiNhan: "",
    nguoiNhanThay: "",
    autoReminder: true,
    capDo: 0,
    nguoiDung: 0,
    nguoiDung2: 0,
    resolveBy: "",
    resolveNote: "",
    status2: 0,
    flagType2: 0,
    doNotShowAgain: true,
    hotelGuid: "",
    id: "",
    userName: ""
}