import { ICreateDTOFolio, IPostingMiniBar } from "common/cashier/model-folio";
import GLobalPkm from "common/global";
export const POSTING_FOLIO_DEFAULT: ICreateDTOFolio = {
    parentGuid: "",
    ngayThang: new Date(),
    flagParent: 0,
    audited: true,
    ma: "",
    dienGiai: "",
    donVi: "",
    donGia: 0,
    soLuong: 0,
    status: 0,
    nguoiDung: 0,
    capDo: 0,
    tag: 0,
    flagType: 0,
    parentMe: 0,
    guest: GLobalPkm.defaultBytes32,
    soPhong: "",
    location: 0,
    rebate: true,
    maTk: "",
    idchild: 0,
    condense: 0,
    suplement: "",
    adjustment: "",
    transferToAr: true,
    nguoiDung2: "",
    debitor: 0,
    transferToAc: true,
    thanhTienVnd: 0,
    thanhTien1Vnd: 0,
    tyGia: 0,
    recIdPh11: 0,
    recIdPh15: 0,
    flagType2: 0,
    outletCode: "",
    dockGuid: GLobalPkm.defaultBytes32,
    packageCode: "",
    hotelGuid: GLobalPkm.defaultBytes32
}
export const POSTING_MINIBAR_DEFAULT: IPostingMiniBar = {
    tsRoomId: GLobalPkm.defaultBytes32,
    tinhChat: "C",
    dataFofolioCreateDTO: POSTING_FOLIO_DEFAULT,
    giaoDichHangHoaMiniBarCreateDTO: {
        ngayThang: new Date(),
        so: "",
        thanhTien: 0,
        tyLeGiamTru: 0,
        soTienGiamTru: 0,
        tongSoTien: 0,
        ghiChu: "",
        nguoiDung: 0,
        capDo: 0,
        guest: GLobalPkm.defaultBytes32,
        freeCharge: false,
        status: 0,
        servicesCharge: 5,
        vatcharge: 10,
        nightAuditorRun: 0,
        hotelGuid: GLobalPkm.defaultBytes32
    },
    chiTietGiaoDichMiniBarCreateDTO:[]
    
}