import { IPostingFoodAndOther, IPostingLaundry } from './../cashier/model-folio';
import GLobalPkm from "common/global";
import { IFixCharge } from 'common/model-hcfg';

export const POSTING_LAUNDRY_DEFAULT: IPostingLaundry = {
    tsRoomId: GLobalPkm.defaultBytes32,
    tinhChat: "C",
    dataFofolioCreateDTO: {
        parentGuid: "",
        ngayThang: new Date(),
        flagParent: 0,
        audited: true,
        ma: "",
        dienGiai: "",
        donVi: "",
        donGia: 0,
        soLuong: 0,
        status: 0,
        nguoiDung: 0,
        capDo: 0,
        tag: 0,
        flagType: 0,
        parentMe: 0,
        guest: GLobalPkm.defaultBytes32,
        soPhong: "",
        location: 0,
        rebate: true,
        maTk: "",
        idchild: 0,
        condense: 0,
        suplement: "",
        adjustment: "",
        transferToAr: true,
        nguoiDung2: "",
        debitor: 0,
        transferToAc: true,
        thanhTienVnd: 0,
        thanhTien1Vnd: 0,
        tyGia: 0,
        recIdPh11: 0,
        recIdPh15: 0,
        flagType2: 0,
        outletCode: "",
        dockGuid: GLobalPkm.defaultBytes32,
        packageCode: "",
        hotelGuid: GLobalPkm.defaultBytes32
    },
    giaoDichLaundryCreateDTO: {
        parent: 0,
        parentGuid: GLobalPkm.defaultBytes32,
        ngayThang: "",
        so: "",
        thanhTien: 0,
        tyLeGiamTru: 0,
        soTienGiamTru: 0,
        tongSoTien: 0,
        ghiChu: "",
        nguoiDung: 0,
        capDo: 0,
        tgtn: new Date(),
        guest: "",
        freeCharge: false,
        status: 0,
        servicesCharge: 0,
        vatcharge: 0,
        nightAuditorRun: 0,
        tongVND: 0,
        expressServiceRatio: 0,
        expressServiceValue: 0,
        hotelGuid: ""
    },
    chiTietGiaoDichLaundryCreateDTOs:[]
    
}

export const POSTING_FOOD_OTHER_DEFAULT: IPostingFoodAndOther = {
    postingCommon: {
        tsRoomId: GLobalPkm.defaultBytes32,
        tinhChat: "C",
        thanhTien: 0,
        businessDate: "string",
        departureDate: "string",
    },
    dataFofolioCreateDTO: {
        parentGuid: "",
        ngayThang: new Date(),
        flagParent: 0,
        audited: true,
        ma: "",
        dienGiai: "",
        donVi: "",
        donGia: 0,
        soLuong: 0,
        status: 0,
        nguoiDung: 0,
        capDo: 0,
        tag: 0,
        flagType: 0,
        parentMe: 0,
        guest: GLobalPkm.defaultBytes32,
        soPhong: "",
        location: 0,
        rebate: true,
        maTk: "",
        idchild: 0,
        condense: 0,
        suplement: "",
        adjustment: "",
        transferToAr: true,
        nguoiDung2: "",
        debitor: 0,
        transferToAc: true,
        thanhTienVnd: 0,
        thanhTien1Vnd: 0,
        tyGia: 0,
        recIdPh11: 0,
        recIdPh15: 0,
        flagType2: 0,
        outletCode: "",
        dockGuid: GLobalPkm.defaultBytes32,
        packageCode: "",
        hotelGuid: GLobalPkm.defaultBytes32
    }
}

export const IFixChargeDefault: IFixCharge = {
    id: 0,
    guid: '',
    parent: 0,
    parentGuid: null,
    ma: '',
    ten: '',
    ghiChu: '',
    maTk1: '',
    maTk2: '',
    maTk3: '',
    maTk4: '',
    soTk1: 0,
    soTk2: 0,
    flagType: 0,
    status: 0,
    tinhChat: '',
    maTk5: '',
    maTk6: '',
    maTk7: '',
    maTk8: '',
    maTk9: '',
    maTk10: '',
    maTk11: '',
    maTk12: '',
    soTk3: 0,
    soTk4: 0,
    soTk5: 0,
    soTk6: 0,
    soTk7: 0,
    soTk8: 0,
    soTk9: 0,
    soTk10: 0,
    tenVn: '',
    maSub1: '',
    maSub2: '',
    maSub3: '',
    maSub4: '',
    groupCode: '',
    subGroupCode: '',
    transactionType: '',
    subGroupType: '',
    subTransactionType: '',
    parentMeGuid: null,
    crossGroupGuid: null,
    tyLeThueVat: 0,
    tyLeThueTtdb: 0,
    tyLePhiDichVu: 0,
    maKhoanMuc: '',
    maVuViec: '',
    maBoPhan: '',
    parentMe: 0,
    hotelGuid: null,
    seq: 0,
    statusRec: 0
}