export * from './bootstrap.slice';
export * from './login.slice';
export * from './app.slice';
export * from './booking.slice';
export * from './hotel.slice';
export * from './company.slice';
export * from './frontdesk/roomplan.slice';
export * from "./frontdesk/frontdesk.slide";
export * from "./report.slice";