export interface MainGuestInfo {
  accountCode: string | null,
  adnumber: string | null
  adress: string | null,
  agentGuid: string | null,
  birthDay: string | null,
  ccexpDate: string | null,
  ccmadeBy: number
  ccno: string | null,
  city: string | null,
  comments: string | null,
  companyGuid: string | null,
  deposit: number
  email: string | null,
  entryDate: string | null,
  entryPort: string | null,
  firstName: string | null,
  groupsGuest: number
  guestName: string | null,
  guestType: string | null,
  languages: string | null,
  nationalityGuid: string | null,
  noOfGuest: number
  passport: string | null,
  passportDate: string | null,
  phone: string | null,
  prefLast: string | null,
  profession: string | null,
  source: string | null,
  taxCode: string | null,
  titlesGuid: string | null,
  visaExpDate: string | null,
  visaNumber: string | null,
}
export interface CompanyProfile {
  id: number,
  geoCode: number,
  ma: string | null,
  ten: string | null,
  diaChi: number,
  diaChiText: string | null,
  giamDoc: string | null,
  dienThoai: string | null,
  fax: string | null,
  taiKhoan: string | null,
  maSoThue: string | null,
  keToanTruong: string | null,
  nguoiGiaoDich: string | null,
  webSite: string | null,
  email: string | null,
  ghiChu: string | null,
  store1: string | null,
  store2: string | null,
  store3: 0,
  store4: 0,
  flagType: 0,
  nguoiDung: 0,
  capDo: 0,
  tgtn: Date | null,
  rateCode: 0,
  accCode: string | null,
  salesId: string | null,
  isPrintRate: true,
  isRateNet: true,
  tenDayDu: string | null,
  guid: string,
  diaChiGuid: string | null,
  rcguid: string | null,
  rateCode2: 0,
  rateCode3: 0,
  nguoiDung2: 0,
  tgtn2: Date | null,
  isVat: true,
  isOta: true,
  resSource: 0,
  namThanhLap: Date | null,
  kind: number,
  loaiHinhHd: string | null,
  thiTruongChinhId: string | null,
  thiTruongChinh: string | null,
  thiTruongPtId: string | null,
  thiTruongPt: string | null,
  thiTruongHuongToiId: string | null,
  thiTruongHuongToi: string | null,
  commission: 0,
  commissionType: string | null,
  hotelGuid: string | null,
  statusRec: 0
}

export interface GuestProfile {
  id: number,
  parent: number,
  guestName: string | null,
  firstName: string | null,
  titlesGuid: string | null,
  adress: string | null,
  bookingCode: string | null,
  zip: string | null,
  city: string | null,
  profession: string | null,
  noOfGuest: number,
  email: string | null,
  phone: string | null,
  languages: string | null,
  country: number,
  nationalityGuid: string | null,
  agentGuid: string | null,
  companyGuid: string | null,
  source: string | null,
  groupsGuest: number,
  prefLast: string | null,
  comments: string | null,
  passport: string | null,
  visaNumber: string | null,
  visaExpDate: string | null,
  entryPort: string | null,
  entryDate: string | null,
  adnumber: string | null,
  ccno: string | null,
  ccexpDate: string | null,
  ccmadeBy: number,
  deposit: number,
  taxCode: string | null,
  flagType: number,
  nguoiDung: number,
  capDo: number,
  tgtn: string | null,
  guestType: string | null,
  birthDay: string | null,
  balance: number,
  idfix: number,
  guid: string | null,
  parentGuid: string | null,
  accountCode: string | null,
  passportDate: string | null,
  khachNn: string | null
  gioiTinh: string | null,
  loaiGiayTo: string | null,
  ngheNghiep: string | null,
  danToc: string | null,
  tonGiao: string | null,
  mucDichLuuTru: string | null,
  quocGiaNew: string | null,
  tinh: string | null,
  huyen: string | null,
  xa: string | null,
  soNhaDuong: string | null,
  hanTamTru: string | null,
  ghiChu: string | null,
  vietKieu: string | null,
  loaiThiThuc: string | null,
  noiCapThiThiThuc: string | null,
  lyDoHetHanTamTru: string | null,
  noiDungLyDoHetHan: string | null,
  visaDate: string | null,
  hotelGuid: string | null,
  statusRec: number,
  groupCode:string | null,
  groupName: string | null,

}

export interface GuestProfileForRoomingList {
  guestName: string | null,
  firstName: string | null,
  titlesGuid: string | null,
  nationalityGuid: string | null,
  passport: string | null,
  birthDay: string | null,
  guid: string | null,
}

export interface GuestProfileNoRsvn {
  parent: number,
  guestName: string | null,
  firstName: string | null,
  titlesGuid: string | null,
  adress: string | null,
  zip: string | null,
  city: string | null,
  profession: string | null,
  noOfGuest: number,
  email: string | null,
  phone: string | null,
  languages: string | null,
  country: number,
  nationalityGuid: string | null,
  agentGuid: string | null,
  companyGuid: string | null,
  source: string | null,
  groupsGuest: number,
  prefLast: string | null,
  comments: string | null,
  passport: string | null,
  visaNumber: string | null,
  visaExpDate: string | null,
  entryPort: string | null,
  entryDate: string | null,
  adnumber: string | null,
  ccno: string | null,
  ccexpDate: string | null,
  ccmadeBy: number,
  deposit: number,
  taxCode: string | null,
  flagType: number,
  nguoiDung: number,
  capDo: number,
  tgtn: string | null,
  guestType: string | null,
  birthDay: string | null,
  balance: number,
  idfix: number,
  parentGuid: string | null,
  accountCode: string | null,
  passportDate: string | null,
  khachNn: string | null
  gioiTinh: string | null,
  loaiGiayTo: string | null,
  ngheNghiep: string | null,
  danToc: string | null,
  tonGiao: string | null,
  mucDichLuuTru: string | null,
  quocGiaNew: string | null,
  tinh: string | null,
  huyen: string | null,
  xa: string | null,
  soNhaDuong: string | null,
  hanTamTru: string | null,
  ghiChu: string | null,
  vietKieu: string | null,
  loaiThiThuc: string | null,
  noiCapThiThiThuc: string | null,
  lyDoHetHanTamTru: string | null,
  noiDungLyDoHetHan: string | null,
  visaDate: string | null,
  hotelGuid: string | null,
}

export interface PostGuestProfileDTO {
  parent: number,
  guestName: string | null,
  firstName: string | null,
  titlesGuid: string | null,
  adress: string | null,
  zip: string | null,
  city: string | null,
  profession: string | null,
  noOfGuest: number,
  email: string | null,
  phone: string | null,
  languages: string | null,
  country: number,
  nationalityGuid: string | null,
  agentGuid: string | null,
  companyGuid: string | null,
  source: string | null,
  groupsGuest: number,
  prefLast: string | null,
  comments: string | null,
  passport: string | null,
  visaNumber: string | null,
  visaExpDate: string | null,
  entryPort: string | null,
  entryDate: string | null,
  adnumber: string | null,
  ccno: string | null,
  ccexpDate: string | null,
  ccmadeBy: number,
  deposit: number,
  taxCode: string | null,
  flagType: number,
  nguoiDung: number,
  capDo: number,
  tgtn: string | null,
  guestType: string | null,
  birthDay: string | null,
  balance: number,
  idfix: number,
  parentGuid: string | null,
  accountCode: string | null,
  passportDate: string | null,
  khachNn: string | null,
  gioiTinh: string | null,
  loaiGiayTo: string | null,
  ngheNghiep: string | null,
  danToc: string | null,
  tonGiao: string | null,
  mucDichLuuTru: string | null,
  quocGiaNew: string | null,
  tinh: string | null,
  huyen: string | null,
  xa: string | null,
  soNhaDuong: string | null,
  hanTamTru: string | null,
  ghiChu: string | null,
  vietKieu: string | null,
  loaiThiThuc: string | null,
  noiCapThiThiThuc: string | null,
  lyDoHetHanTamTru: string | null,
  noiDungLyDoHetHan: string | null,
  visaDate: string | null,
  hotelGuid: string | null
}

export interface MasterAndMemberProfiles {
  masterProfile: GuestProfile,
  memberProfiles: PostGuestProfileDTO[]
}

export interface MasterAndMembersGuid {
  masterGuestGuid: string | null,
  guestGuid: string[]
}

export interface ShortGuestProfileData {
  titlesGuid: string,
  firstName: string,
  lastName: string,
  bookingCode: string
}

export interface ShortCompanyProfileData {
  groupCode: string,
  groupName: string
}

export interface HistoryOfProfiles {
  arrival: string,
  room: string,
  fullName: string,
  rate: number,
  departure: string
}

export interface HistoryYearOfProfiles {
  year: number,
  nights: number,
  room: string,
  revenue: number,
  fbRevenue: number
}

export interface dataGuest {
  fullName: string,
  guestGuid: string,
  tsRoomId: string
}